apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: lornu-dev

commonLabels:
  lornu.ai/environment: development
  lornu.ai/managed-by: kustomize

replicas:
- name: lornu-ai
  count: 1
