- op: remove
  path: /metadata/annotations/kubernetes.io~1ingress.class
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1scheme
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1target-type
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1listen-ports
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1ssl-redirect
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1healthcheck-path
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1healthcheck-interval-seconds
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1healthcheck-timeout-seconds
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1healthy-threshold-count
- op: remove
  path: /metadata/annotations/alb.ingress.kubernetes.io~1unhealthy-threshold-count
