apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
- targetgroupbinding.yaml

namespace: lornu-prod

commonLabels:
  lornu.ai/env: production

patches:
- target:
    kind: Deployment
    name: lornu-ai
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
- target:
    kind: Ingress
    name: lornu-ai
  path: ingress-patch.yaml
