apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
- cert-manager
- secrets.yaml

namespace: lornu-prod

commonLabels:
  lornu.ai/env: production

patches:
- target:
    kind: Deployment
    name: lornu-ai
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
- target:
    kind: Ingress
    name: lornu-ai
  patch: |-
    - op: add
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-prod
    - op: add
      path: /metadata/annotations/cert-manager.io~1certificate-name
      value: lornu-ai-tls
    - op: add
      path: /spec/tls
      value:
      - hosts:
        - example.com
        - api.example.com
        secretName: lornu-ai-tls
