apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: lornu-staging

commonLabels:
  lornu.ai/environment: staging
  lornu.ai/managed-by: kustomize

replicas:
- name: lornu-ai
  count: 2
