apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lornu-dev

resources:
  - ../../base

images:
  - name: lornu-ai
    newName: lornu-ai
    newTag: local

patches:
  - path: patches/resources.yaml
