apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lornu-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: lornu-ai
    newName: us-central1-docker.pkg.dev/gcp-lornu-ai/lornu-ai/lornu-ai
    newTag: latest

patches:
  - path: patches/resources.yaml
  - path: patches/serviceaccount.yaml
