apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lornu-dev

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- patches/local-env.yaml
- patches/local-service.yaml

images:
- name: lornu-ai
  newTag: latest
