apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: lornu-ai
      app.kubernetes.io/part-of: lornu-ai

namePrefix: ""
namespace: default
