apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
images:
- name: lornu-ai
  newName: lornu-registry.localhost:5000/lornu-ai
  newTag: local
patches:
- path: deployment-patch.yaml
- path: configmap-patch.yaml
