apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: lornu-prod
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: lornu-ai
  - target:
      kind: Ingress
      name: lornu-ai
    patch: |-
      - op: remove
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
