apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lornu-stage
resources:
- ../../base
- namespace.yaml
namePrefix: staging-
commonLabels:
  app.kubernetes.io/name: lornu-ai
  lornu.ai/environment: staging
  lornu.ai/managed-by: terraform-cloud
  lornu.ai/asset-id: lornu-ai-final-clear-bg
images:
- name: lornu-ai
  newName: 148080843892.dkr.ecr.us-east-1.amazonaws.com/lornu-ai-staging
  newTag: latest
replicas:
- name: staging-lornu-ai
  count: 2
patches:
- path: deployment-patch.yaml
configMapGenerator:
- name: lornu-ai-config
  behavior: merge
  literals:
  - environment=staging
