apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
images:
- name: lornu-ai
  newName: placeholder-registry/lornu-ai
  newTag: latest
patches:
- path: deployment-patch.yaml
