apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namePrefix: staging-
images:
- name: lornu-ai
  newName: <AWS_ECR_REGISTRY>
  newTag: ${{ github.sha }}
patches:
- path: deployment-patch.yaml
