apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: staging-
images:
- name: lornu-ai
  newName: <AWS_ECR_REGISTRY>
<<<<<<< HEAD
  newTag: <IMAGE_TAG>
patches:
- path: deployment-patch.yaml
